name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Deploy to server
          uses: appleboy/scp-action@v0.1.4
          with: 
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
            source: "."
            target: "~/htdocs/api.6yuwei.com"
            
        - name: Restart PM2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
            script: |
              sudo ln -s "$NVM_DIR/versions/node/v18.16.1/bin/pm2" "/usr/local/bin/pm2"
              cd ~/htdocs/api.6yuwei.com
              pm2 restart all